services:
  postgres:
    container_name: postgre_db_project
    build: .
    restart: always
    ports:
      - "5433:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_db_project
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "80:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
