CALL add_genre('Sci-Fi'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Shoujo Ai'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Samurai'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Action'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Josei'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Sports'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Yaoi'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Shoujo'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Horror'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Space'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Police'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Seinen'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Supernatural'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Yuri'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Demons'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Unknown'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Historical'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Drama'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Dementia'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Thriller'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Fantasy'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Kids'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Shounen Ai'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Harem'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Psychological'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Super Power'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Vampire'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Mystery'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Romance'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Shounen'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Ecchi'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Hentai'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Game'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Music'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Mecha'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Cars'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Martial Arts'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Adventure'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Military'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Comedy'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Magic'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Slice of Life'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('School'::VARCHAR, 'No description provided'::TEXT);
CALL add_genre('Parody'::VARCHAR, 'No description provided'::TEXT);