CALL add_genre('Historical'::VARCHAR, NULL);
CALL add_genre('Romance'::VARCHAR, NULL);
CALL add_genre('Psychological'::VARCHAR, NULL);
CALL add_genre('Unknown'::VARCHAR, NULL);
CALL add_genre('Mecha'::VARCHAR, NULL);
CALL add_genre('Super Power'::VARCHAR, NULL);
CALL add_genre('Shounen'::VARCHAR, NULL);
CALL add_genre('Hentai'::VARCHAR, NULL);
CALL add_genre('Horror'::VARCHAR, NULL);
CALL add_genre('Ecchi'::VARCHAR, NULL);
CALL add_genre('Military'::VARCHAR, NULL);
CALL add_genre('Shoujo'::VARCHAR, NULL);
CALL add_genre('Space'::VARCHAR, NULL);
CALL add_genre('Josei'::VARCHAR, NULL);
CALL add_genre('Demons'::VARCHAR, NULL);
CALL add_genre('Parody'::VARCHAR, NULL);
CALL add_genre('Music'::VARCHAR, NULL);
CALL add_genre('Kids'::VARCHAR, NULL);
CALL add_genre('Sci-Fi'::VARCHAR, NULL);
CALL add_genre('Comedy'::VARCHAR, NULL);
CALL add_genre('Shoujo Ai'::VARCHAR, NULL);
CALL add_genre('Dementia'::VARCHAR, NULL);
CALL add_genre('Police'::VARCHAR, NULL);
CALL add_genre('Supernatural'::VARCHAR, NULL);
CALL add_genre('Thriller'::VARCHAR, NULL);
CALL add_genre('Yaoi'::VARCHAR, NULL);
CALL add_genre('Game'::VARCHAR, NULL);
CALL add_genre('Cars'::VARCHAR, NULL);
CALL add_genre('Shounen Ai'::VARCHAR, NULL);
CALL add_genre('Yuri'::VARCHAR, NULL);
CALL add_genre('Slice of Life'::VARCHAR, NULL);
CALL add_genre('Sports'::VARCHAR, NULL);
CALL add_genre('Action'::VARCHAR, NULL);
CALL add_genre('Adventure'::VARCHAR, NULL);
CALL add_genre('Seinen'::VARCHAR, NULL);
CALL add_genre('Samurai'::VARCHAR, NULL);
CALL add_genre('Martial Arts'::VARCHAR, NULL);
CALL add_genre('Drama'::VARCHAR, NULL);
CALL add_genre('School'::VARCHAR, NULL);
CALL add_genre('Fantasy'::VARCHAR, NULL);
CALL add_genre('Magic'::VARCHAR, NULL);
CALL add_genre('Vampire'::VARCHAR, NULL);
CALL add_genre('Harem'::VARCHAR, NULL);
CALL add_genre('Mystery'::VARCHAR, NULL);