CALL add_studio('Lerche'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DR Movie'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tear Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Anime Antenna Iinkai'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Animation Do'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('helo.inc'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Junio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AXsiZ'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bakken Record'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Garden Culture'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Albacrow'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Flavors Soft'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Knack Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Soeishinsha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Soyep'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Automatic Flowers Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Drive'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Toho'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Nue'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Artland'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yostar Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Egg'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tele-Cartoon Japan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Typhoon Graphics'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ChuChu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LIDENFILMS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Decovocal'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bones'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Office DCI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Graphinica'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Bind'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio M2'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ajia-Do'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tsukimidou'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CUCURI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Maho Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PPM'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DLE'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Group TAC'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kitty Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pops Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Echoes'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tomovies'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Colored-Pencil Animation Design'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kokusai Eigasha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Creators in Pack'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('OLM Digital'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('David Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Peak Hunt'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('W-Toon Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Front Line'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('HeART-BIT'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio OX'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sublimation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Seven Arcs Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Chizu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Liberty Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('P.A. Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LICO'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pancake'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Production +h.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BeSTACK'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gakken Eigakyoku'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Opera House'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TYO'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Azeta Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CygamesPictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Qualia Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Zexcs'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Trigger'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Brio Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Telescreen'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('8bit'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tezuka Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Aurum Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Geno Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SPEED'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sakura Create'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio! Cucuri'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Green Monster Team'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('81 Produce'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Welz Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yokohama Animation Lab'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SANZIGEN'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wolf Smoke Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('dwarf'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Venet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Palm Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yumeta Company'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shirogumi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Filmlink International'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Office Take Off'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Imagineer'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio 3Hz'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LMD'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Dadashow'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pollyanna Graphics'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Egg Firm'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Samsara Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Office Nobu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Plum'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Taomee'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('I.Gzwei'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Urban Product'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Piko Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shaft'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Lilix'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Blue Cat'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dai Nippon Printing'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BOOTLEG'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DMM.futureworks'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('C-Station'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dynamo Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PONOS Corporation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Seven Stone Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tokyo Movie Shinsha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Blanc'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Manglobe'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Lings'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mushi Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Actas'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tokyo Media Connections'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('l-a-unch・BOX'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Image House'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('UWAN Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ascension'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Annapuru'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('The Answer Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tengu Kobo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Maxilla'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KOO-KI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Comet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Directions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Millepensee'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Irawias'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Chaos Project'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('An DerCen'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dangun Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wit Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KeyEast'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GEEK TOYS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Signal.MD'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sunwoo Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Jinnis Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Puzzle Animation Studio Limited'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Vasoon Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Djinn Power'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Cyclone Graphics'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ashi Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio 88'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Hibari'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Oz'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Trinet Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tonko House'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Phoenix Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PrimeTime'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nippon Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TOHO animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bee Media'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Himajin Planning'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TAKI Corporation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Flad'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Asatsu DK'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Digital Frontier'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GARDEN LODGE'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ezόla'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Echo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BUILD DREAM'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Thundray'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Natural High'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Connect'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mary Jane'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wan Wei Mao Donghua'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gainax'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Saetta'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Milky Animation Label'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Production IMS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Space Neko Company'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DRAWIZ'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KSS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Charaction'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Silver'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC Spirits'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CGCG Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Grouper Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GANSIS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tama Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Arvo Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bandai Spirits'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Brains Base'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Genco'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Signpost'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('JCF'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio G-1Neo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Remic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Doga Kobo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Karaku'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC Takarazuka'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Team YokkyuFuman'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mook DLE'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Visual 80'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nice Boat Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('L²Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Chiptune'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TANOsim'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bandai Visual'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bandai Namco Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gaina'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ark'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ekura Animal'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LandQ studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Usagi Ou'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Ponoc'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Fantasia'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Deen'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Qianqi Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Beijing Rocen Digital'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tokyo Movie'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Acca effe'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Stingray'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio 9 MAiami'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Zero-G'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('pH Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Egg'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Meditation With a Pencil'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Odolttogi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pie in the sky'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sunrise Beyond'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nihon Ad Systems'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MAPPA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Planet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yamamura Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Schoolzone'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shuka'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ishimori Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Majin'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Diomedéa'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Animal'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ixtl'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shin-Ei Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SILVER LINK.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Rising Force'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('October Media'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Office AO'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Iyasakadou Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio LAN'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Bogey'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('A-Line'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Public & Basic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Daewon Media'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Japan Taps'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('2:10 AM Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KAGAYA Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Maro Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CANDY BOX'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Fuji TV'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sugar Boy'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nikkatsu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Arch Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Green Bunny'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Animation Staff Room'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Hoods Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Craftar Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('The Monk Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Rabbit Machine'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bouncy'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Poncotan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kaeruotoko Shokai'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Marine Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('APPP'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tomoyasu Murata Company'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yaoyorozu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tatsunoko Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Future Planet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Toho Interactive Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Beijing Huihuang Animation Company'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kino Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shinkuukan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Marvy Jack'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Takahashi Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Oddjob'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio UGOKI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nut'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Anima&Co.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Magic Bus'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ripple Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Assez Finaud Fabric'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('NAZ'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ripromo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Animaruya'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Radix'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dongyang Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Visual Flight'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Congzhuo Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pink Pineapple'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CoMix Wave Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Indeprox'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Picture Magic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DMM pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Durufix'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Revoroot'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Moss Design Unit'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Office Takeout'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kazuki Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PoRO'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('B.CMAY PICTURES'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio DURIAN'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Suna Kouhou'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('NHK Enterprises'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Emon'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Fenz'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bridge'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Madhouse'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pony Canyon'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio March'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Romanov Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bee Train'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Queen Bee'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mokai Technology'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Piso Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TROYCA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Pierrot'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Husio Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Kikan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AQUA ARIS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wawayu Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Flag'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Strawberry Meets Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Plus Heads'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio W.Baba'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ACC Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shochiku Animation Institute'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Boyan Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Sign'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TNK'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pb Animation Co. Ltd.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tencent Penguin Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Suzuki Mirano'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('HOTZIPANG'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yamato Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('production doA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio elle'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MMDGP'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ElectromagneticWave'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Colorido'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Production Reed'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Seven'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Hal Film Maker'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('T-Rex'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GEMBA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kachidoki Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Hakk'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shimogumi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Korumi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wolfsbane'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Spoon'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sparkly Key Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Eromatick'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gonzo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Keica'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Team TillDawn'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Idol'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Teatro Nishi Tokyo Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GoHands'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Making Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('C2C'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ILCA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dynamic Planning'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Animation 21'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC Build'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Toei Video'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CloverWorks'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('FOREST Hunting One'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Enishiya'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC Classic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Zealot'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Code'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Animation Planet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Speed Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Moriken'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Youmex'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Rikuentai'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Zero-G Room'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nomad'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Barnum Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Suiseisha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('StoryRiders Co. Ltd.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('EDGE'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ufotable'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Palette'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Composition Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Lesprit'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Twilight Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Creators Dot Com'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('White Fox'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('10Gauge'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Fifth Avenue'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GEN Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DandeLion Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tencent Animation & Comics'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Enoki Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Encourage Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('M.S.C'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Avex Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('drop'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Motion Magic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('G-angle'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Science SARU'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Monsters Egg'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Kyuuma'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Yi Chen Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mirai Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Anpro'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Purple Cow Studio Japan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Gokumi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio VOLN'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shogakukan Music & Digital Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sparky Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Y.O.U.C'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Idea Factory'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MooGoo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Satelight'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('RAMS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dwango'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gold Bear'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mili Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Arms'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('WAO World'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Spell Bound'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Neft Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TMS Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Production GoodBook'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Digital Media Lab'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Asura Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Red Dog Culture House'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kinema Citrus'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Academy Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Marza Animation Planet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Jumonji'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CyberConnect2'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('IMAGICA Lab.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Haoliners Animation League'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shueisha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Jumondo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shenying Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Signal'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Arcturus'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Coa'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TYO Animations'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Three-d'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sprite Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Flat Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Polygon Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MASTER LIGHTS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Calf Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Larx Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('iDRAGONS Creative Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Steve N Steven'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Anime R'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('W+K Tokyo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('DAX Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('D.A.S.T.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('EMT Squared'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Issen'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SBS TV Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Minakata Laboratory'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Collaboration Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Oh! Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Original Force'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pastel'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Media Bank'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('3xCube'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Hiro Media'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tecarat'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Qubic Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CG Year'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Namu Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SELFISH'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Japan Vistec'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Kai'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Live'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Giga Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Z5'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Robot Communications'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tomason'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Childrens Playground Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Imagin'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kaname Productions'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KIZAWA Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Cookie Jar Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Magia Doraglier'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Think Corporation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Khara'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('animate Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Jam'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio WHO'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Seven Arcs'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Matrix'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ordet'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Twin Engine'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('OLM'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Artmic'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio 1st'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Zero'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sotsu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dongwoo A&E'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Agent 21'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dancing CG Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('KJJ Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MS Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Binzo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Crocodile'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nur'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Wei Chuang Jiang Xin'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('FILMONY'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Fanworks'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Heewon Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TriF Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Unicorn'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Nanahoshi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Live2D Creative Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nippon Ramayana Film Co.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Super Normal Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ether Kitten'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nishiki Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Unknown'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gallop'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('XFLAG'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio A-CAT'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Creatures Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TUBA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Topcraft'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Success Corp.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Square Enix Visual Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ASK Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Big Bang'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('GRIZZLY'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ginga Ya'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('teamKG'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tohokushinsha Film Corporation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('A-1 Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BigFireBird Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Arcs Create'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('D & D Pictures'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Blade'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LX Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('View Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Asread'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kamikaze Douga'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('feel.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ruo Hong Culture'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MORIE Inc.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Triple X'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC ASTA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Toei Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sanrio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Xebec'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Hotline'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('E&G Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Saigo no Shudan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('P.I.C.S.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ZIZ Entertainment (ZIZ)'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Okuruto Noboru'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio CA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Khronos'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Guton Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('B&T'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shanghai Animation Film Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio World'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Circle Tribute'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Amuse'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BYMENT'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Karasfilms'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Telecom Animation Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Amber Film Works'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Imagica Imageworks'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('monofilmo'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Bibury Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('T.P.O'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Asahi Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Felix Film'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kazami Gakuen Koushiki Douga-bu'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Wombat'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Coastline Animation Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Mook Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('BreakBottle'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Chippai'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Aubec'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sega Interactive'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Light Chaser Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Minami Machi Bugyousho'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Project No.9'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Anima'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Meruhensha'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('YHKT Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gosay Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tamura Shigeru Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sunrise'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Lay-duce'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Lapin Track'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('A.C.G.T.'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('HS Pictures Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Rikka'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Next Media Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Oxybot'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('A-Real'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Kafka'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('SynergySP'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ankama Animations'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Life Work'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Shanghai Foch Film Culture Investment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Akatsuki'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AT-2'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Square Enix'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nakamura Production'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Nexus'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('G&G Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('NHK'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Eiken'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('domerica'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Kelmadick'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio PuYUKAI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pierrot Plus'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PRA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Onionskin'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('EKACHI EPILKA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Grom'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Dai-Ichi Douga'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Primastea'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('CLAP'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Hokiboshi'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Suspenders'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Rockwell Eyes'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Pine Jam'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ORENDA'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Ppuri'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gathering'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kate Arrow'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Trans Arts'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Panmedia'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Lide'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('REALTHING'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Take Off'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('LEVELS'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('OZ'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kenji Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('ENGI'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Orange'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC Frontier'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Sola Digital Arts'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('MAT'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Joker Films'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tri-Slash'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Will Palette'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Picograph'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Gainax Kyoto'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Digital Network Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Triangle Staff'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('AIC PLUS+'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kyotoma'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kanaban Graphics'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Milky Cartoon'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Passione'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Daume'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('TYMOTE'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('G-Lam'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Darts'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Ishikawa Pro'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Painting Dream'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Platinum Vision'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Buemon'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Ghibli'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tong Ming Xuan'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Kyoto Animation'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('J.C.Staff'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('PERIMETRON'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('RG Animation Studios'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Panda Factory'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Picona'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Production I.G'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tokyo Kids'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Hoods Drifters Studio'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio Core'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Studio 4°C'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Vega Entertainment'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Rabbit Gate'::VARCHAR, 'No description provided'::TEXT);
CALL add_studio('Tsuchida Productions'::VARCHAR, 'No description provided'::TEXT);